<h2 itemprop="headline">A tengerimalac		</h2>
</div><div itemprop="articleBody">
<p>A tengerimalacok társas lények, az egyedül tartott malacka betegesebb, immunrendszere gyengébb, és bármennyit is foglalkozunk vele, igazán boldog csak egy másik tengerimalac mellett lehet.</p>
<p>Természetes közegében 6-7 fős csapatokban élnek, melyet egy hím vezet. A hím fenntartja a békét a civakodó nőstények között és védi a csapatot a betolakodóktól. Csak az a hím lehet a csapat élén, akire a nőstények felnéznek, és feltétel nélkül elfogadják, ezért nem mindegy, milyen (ivartalanított!) hímet választunk a nőstényünk vagy nőstényeink mellé, bővebb információ itt.</p>
<p>A tengerimalac – sok más kisrágcsálóval ellentétben - nappali állat, így nem kell tartanunk attól, hogy az egész napot átalussza, majd egész éjjel hangosan motoszkál. Mivel fűevő, a nap nagy részét széna rágcsálásával tölti. Gondoskodjunk róla bőséges, jó minőségű széna adagolásával, hogy ezt az igényét folyamatosan kielégíthesse!</p>
<p>Érdekesség, hogy a tengerimalacok hangos „kiabálása”, amikor ennivalót kér, csak nekünk, embereknek szól, kizárólag számunkra fejlesztették ki a kommunikáció e módját. Hangskálájuk elég széles, egymással igen halkan, gyakran ultrahangokkal kommunikálnak. A jól szocializált, gazdiban bízó tengerimalac jellemzője, hogy hangosan jelzi, ha elérkezett a vacsora ideje.</p>
<p>A visítás lehet még a fájdalom jele, de az egészen más hang, mint mikor éhes. Az egy kimondottan panaszos, fájdalomról árulkodó hang, könnyen felismerhető. Ha ilyet hallunk, mindig vizsgáljuk meg az okát.</p>
<p>Ölünkben simogatva prüntyögő, nyünyörgő hangokkal adja tudtunkra, mennyire jól esik neki a szeretgetés. Ha egy idő után motoszkálni kezd, nyugtalan lesz, tegyük vissza a ketrecébe, valószínűleg pisilnie kell!</p>
<p>Természetes közegében a finom falatok után való kutatáshoz, legelészéshez nagy területet kell bejárnia, ezért a mozgásigénye nagy, még ha tömzsi testalkatából nem is ezt a következtetést vonnánk le elsőre. Ahhoz, hogy testsúlya és általános állapota egészséges maradjon, biztosítsunk neki elegendő mozgásteret. A megfelelő méretű ketrec elengedhetetlen, a minimum méret két állat esetén 100 x 50 cm alapterület, három malacnál 120 x 50 cm, és így tovább, de természetesen minél nagyobb, annál jobb. A ketrecet rendezzük be izgalmasan, biztosítsunk minden malacnak búvóhelyet és lehetőséget arra, hogy ugrándozhasson. A megfelelően tágas ketrecben elhelyezhetünk vastagabb műanyagcsöveket, ill. függőágyat, almafaágat, fűből font bújókat stb., így többet mozognak, ugrándoznak.A ketrecébe sose tegyünk futókereket, bármilyen labdát, ezekkel játszani nem tud, és sérülést okozhatnak! Időnként biztonságos helyen hagyjuk szabadon futkározni, felfedezni, hálás lesz érte! Erre megfelelő a konyha, fürdő-szoba vagy olyan helyek, melyeknek padlózatát könnyű tisztítani. A társakat mindig együtt tegyük ki, így felfedező utak még érdekesebbé válnak, a kíváncsibb malackát követi a félénkebb, egymást bátorítják. Szaladgálnak, kergetőznek, örömmel fogadják, ha kartondobozokból készített labirintusokba bújhatnak. Vastag műanyag vagy karton csöveket is letehetünk, ha ezekben kényelmesen elférnek. A vécépapír üres papírhengerét kibélelhetjük szénával, számos tengerimalac szívesen eljátszik ezzel.</p>
<p>Vegyük figyelembe, hogy a mód, ahogyan egy rágcsáló játszik, eltér a kutyák és macskák játékától. Őket nem ingerli ugyanis annyira a mozgás, hiszen növényevők. Ne várjuk el tőlük, hogy az elgurított labda után szaladjanak, mert nem fognak. Ez nem azért van, mert buták lennének, pusztán nincs meg bennük az a reflex, hogy kergetniük kell a zsákmányt.</p>
<p>A tengerimalacok eleinte bizalmatlanok, főleg, ha kereskedésből származnak. Nagyon fontos, hogy hagyjunk nekik elég időt, hogy megszokják új környezetüket! A félénk malacka eleinte elszalad, ha embert lát. Ám egy megszelídült tengerimalac nagyon barátságossá válik, egy finom falat vagy simogatás reményében a rácshoz rohan, ha meghallja gazdiját közeledni. Ám ez nem megy egyik napról a másikra, itt egy kis segítség, hogyan nyerjük el malackánk bizalmát. Ne feledjük, a tengerimalac zsákmányállat, így számukra az ijedősség és bizalmatlanság a természetben a túlélés eszköze volt. Érdekesség, hogy sok tengerimalac ma is rémülten menekül, ha az ablak előtt elrepül egy nagyobb madár. Ez is egy természetes ösztön, hiszen a ragadozó madarak komoly veszélyt jelentenek rájuk. (Ezért, ha kerti kifutóba helyezzük őket, erre is gondoljunk!)</p>
<p>A fiatal tengerimalacok nagyon játékosak, de ez idősebb korukra sem múlik el nyomtalanul. Hangulatuk tetőfokán pattogatott kukoricaként ugrálnak a magasba, a levegőben akár 180º-os hirtelen fordulatot tesznek, majd merőben más helyzetben érnek földet, társaikat is ugrálásra, jókedvre késztetve. Ezt a mulatságos pattogást „popcornozás”-nak nevezik. Kifejezetten ragályos, ha egyikük elkezdi, öröme gyakran átragad a többiekre. Popcornozást kiválthat akár a kajás zacskó csörgése is. ( Mielőtt a tengerimalac-tartás mellett döntünk, vegyük figyelembe igényeit, és azt, hogy 6-8 évig is élnek. Ez idő alatt végig gondoskodnunk kell az igényeinek megfelelő környezetről és táplálékról, valamint arról, hogy ha megbetegszik, a lehető leghamarabb eljussunk vele egy hozzáértő, megbízható állatorvoshoz. Ajánlott állatorvosok listája elérhető honlapunkon.)</p>
<p>A tengerimalac a külső hatásokra érzékeny, a rossz tartási körülményektől, huzattól, koszos, nedves ketrectől, rossz minőségű tápláléktól könnyen megbetegszik.</p>
<p>Ám ha megfelelő körülményeket biztosítunk számára, hosszú ideig szerető társunk lehet ez a mókás, imádni való kisállat.</p>
<p><strong>Malactartási kódex letölthető formátumban:</strong> <a title="Malactartási kiskódex" href="/images/malactartasi-kodex.pdf" target="_blank" rel="noopener noreferrer">letöltés</a></p> 	</div>
